POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjYyNzkyMjQyfQ.ZIwAsgDDfpV6B2W6h8cfF8w0QqxoTjMIpBfM_mwyPfk

###

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjYyNzkyMjQyfQ.ZIwAsgDDfpV6B2W6h8cfF8w0QqxoTjMIpBfM_mwyPfk


###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjYyNzkyMjQyfQ.ZIwAsgDDfpV6B2W6h8cfF8w0QqxoTjMIpBfM_mwyPfk

###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjYzMTQ5MDI2fQ.bUrsAPIe6EGBSST09qLL2EHLjWnBKwwCI5MN6D0dhLY

###

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjYzMTQ5MDI2fQ.bUrsAPIe6EGBSST09qLL2EHLjWnBKwwCI5MN6D0dhLY
Content-Type: application/json

{
   "tweet": "The Mornings sjsj ajhfbjhadbf sjhfbasjhfb ,shfbashbf s,hbfashb"
}